version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # for root web project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
